<<#

# ----------------------------------------------------------------------
# |
# |  _Template.template.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-05-18 09:34:21
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------

The following values must be set by child templates:

  - type [required = 'callable', 'manual']
  - is_execute [required, bool]

#>>

<<% if is_execute %>>
  <<% set template_command = "Execute" %>>
<<% else %>>
  <<% set template_command = "Validate" %>>
<<% endif %>>

<<% if type == "callable" %>>
name: "[callable] Invokes MarkdownModifier with '<<< template_command >>>'"

on:
  workflow_call:

<<% elif type == "manual" %>>
name: "Invoke MarkdownModifier with '<<< template_command >>>'"

on:
  workflow_dispatch:

<<% else %>>
unknown
<<% endif %>>

    inputs:
      wiki_repo:
        type: string
        required: true
        description: "Name of the wiki repository to modify or validate (e.g. <username>/<repository>)."

<<% if is_execute %>>
      markdown_modifier_commit_message:
        type: string
        required: false
        default: ""
        description: "Commit message used to commit any changes made by MarkdownModifier. No commit will be made if this message is empty."
<<% endif %>>

      markdown_modifier_command_line_args:
        type: string
        required: false
        default: ""
        description: "Command line arguments to pass to MarkdownModifier when invoked."

      markdown_modifier_branch:
        type: string
        required: false
        default: main_stable
        description: "Source branch associated with the MarkdownModifier repository."

      force_setup:
        type: boolean
        required: false
        description: "Appends the '--force' flag when setting up repositories."
        default: false

      force_activate:
        type: boolean
        required: false
        description: "Appends the '--force' flag when activating repositories."
        default: false

      no_cache:
        type: boolean
        required: false
        description: "Disable caching."
        default: false

run-name: ${{ github.run_number }} [${{ github.actor }}] for Wiki

jobs:
  _3f6a9198-4152-4f80-a354-47290145b629:
    name: "Markdown Modifier (<<< template_command >>>)"
    uses: davidbrownell/v4-Common_MarkdownModifier/.github/workflows/_callable_markdown_modifier_impl.yaml@CI-v1
    with:
      wiki_repo: ${{ inputs.wiki_repo }}
      markdown_modifier_command: <<< template_command >>>
      markdown_modifier_command_line_args: "${{ inputs.markdown_modifier_command_line_args }}"

<<% if is_execute %>>
      markdown_modifier_commit_message: ${{ inputs.markdown_modifier_commit_message }}
<<% endif %>>

      repo_name: davidbrownell/v4-Common_MarkdownModifier
      repo_branch: ${{ inputs.markdown_modifier_branch }}
      configuration: standard

      job_name_prefix: Markdown Modifier
      os: ubuntu-latest
      bootstrap_branch_overrides: ""

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}
