# ----------------------------------------------------------------------
# |
# |  event_on_pr.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-05-03 10:46:31
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on pull request"
run-name: "${{ github.run_number }} [${{ github.actor }}] ${{ github.head_ref }} -> ${{ github.base_ref }}"

on:
  pull_request:
    branches:
      - main

jobs:
  _9938d22d-5952-4123-8f5c-14a533572e9f:
    name: "Validate (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_MarkdownModifier/.github/workflows/validate.yaml@CI-latest
    with:
      repo_branch: ${{ github.head_ref }}

  _63c3694d-ae80-4192-a105-231e597f7833:
    name: "Validate Pull Request (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate_pull_request.yaml@CI-latest
    with:
      job_name_prefix: "v4-Common_MarkdownModifier"
      is_mixin_repository: false
      repo_name: davidbrownell/v4-Common_MarkdownModifier
      repo_branch: ${{ github.head_ref }}
      os: ubuntu-latest
      configuration: dev
