# ----------------------------------------------------------------------
# |
# |  manual_markdown_modifier_execute.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-05-18 09:41:32
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
<<% extends "../_Template.template.yaml" %>>
<<% set type="manual" %>>
<<% set is_execute = true %>>
