# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         actions/markdown_modifier/action.jinja2.yml
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-05-15 12:45:39
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Markdown Modifier
description: Runs `MarkdownModifier` on the repository.

inputs:
  github_workspace:                         { type: string, required: true }

  script_extension:                         { type: string, required: true }
  shell_name:                               { type: string, required: true }

  activate_statement:                       { type: string, required: true }

  wiki_repo:                                { type: string, required: true }
  markdown_modifier_command:                { type: string, required: true }
  markdown_modifier_command_line_args:      { type: string, required: false }
  markdown_modifier_commit_message:         { type: string, required: false }

runs:
  using: composite
  steps:
    - name: Checkout Wiki Source
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.wiki_repo }}
        path: wiki

    - name: "Markdown Modifier (${{ inputs.markdown_modifier_command }})"
      shell: ${{ inputs.shell_name }}
      run: ${{ inputs.activate_statement }} && MarkdownModifier${{ inputs.script_extension }} ${{ inputs.markdown_modifier_command }} "${{ inputs.github_workspace }}/wiki" ${{ inputs.markdown_modifier_command_line_args }} --debug

    - name: Commit Potential Changes
      if: ${{ (inputs.markdown_modifier_command == 'Execute' && inputs.markdown_modifier_commit_message != '') }}
      shell: ${{ inputs.shell_name }}
      run: |-
        cd "${{ inputs.github_workspace }}/wiki" > /dev/null

        git status --short > /dev/null
        if [[ ${generation_error} != 0 ]]
        then
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@DoesNotExist.com"

          echo "\nCommitting content..."
          git commit -a -m "${{ inputs.markdown_modifier_commit_message }}"

          echo "\nPushing content..."
          git push
        else
          echo "No content to commit."
        fi
