# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/manual_markdown_modifier_validate.jinja2.yaml
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  manual_markdown_modifier_validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-05-18 09:41:32
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------


name: "Invoke MarkdownModifier with 'Validate'"

on:
  workflow_dispatch:


    inputs:
      wiki_repo:
        type: string
        required: true
        description: "Name of the wiki repository to modify or validate (e.g. <username>/<repository>)."


      markdown_modifier_command_line_args:
        type: string
        required: false
        default: ""
        description: Command line arguments to pass to MarkdownModifier when invoked."

      markdown_modifier_branch:
        type: string
        required: false
        default: main_stable
        description: Source branch associated with the MarkdownModifier repository.

      force_setup:
        type: boolean
        required: false
        description: "Appends the '--force' flag when setting up repositories."
        default: false

      force_activate:
        type: boolean
        required: false
        description: "Appends the '--force' flag when activating repositories."
        default: false

      no_cache:
        type: boolean
        required: false
        description: "Disables caching."
        default: false

run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

jobs:
  _3f6a9198-4152-4f80-a354-47290145b629:
    name: "Markdown Modifier (Validate)."
    uses: davidbrownell/v4-Common_MarkdownModifier/.github/workflows/_callable_markdown_modifier_impl.yaml@CI-v1
    with:
      wiki_repo: ${{ inputs.wiki_repo }}
      markdown_modifier_command: Validate
      markdown_modifier_command_line_args: "${{ inputs.markdown_modifier_command_line_args }}"


      repo_name: davidbrownell/v4-Common_MarkdownModifier
      repo_branch: ${{ inputs.markdown_modifier_branch }}
      configuration: standard

      job_name_prefix: markdown_modifier
      os: ubuntu-latest
      bootstrap_branch_overrides: ""

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}
